#!/bin/bash

# prepare calliope
cd calliope
yt clean
yt update
rm -r source/*
cp -r ../../../abbozza-calliope/lib/build/calliope/* .
cp -r ../../../abbozza-calliope/lib/build/common/* source
yt build

cd ../microbit
yt clean
yt update
rm -r source/*
cp -r ../../../abbozza-calliope/lib/build/microbit/* .
cp -r ../../../abbozza-calliope/lib/build/common/* source
# yt build

cd ..

